CREATE TABLE IF NOT EXISTS `deployment_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `chain_type` SMALLINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deployment_db`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `deployment_template_id` BIGINT NOT NULL,
   `db_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deployment_node`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `deployment_template_id` BIGINT NOT NULL,
   `node_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `db_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `cloud_vendor` TINYINT NOT NULL,
   `db_role` SMALLINT NOT NULL,
   `db_type` VARCHAR(255) NOT NULL,
   `machine_type` VARCHAR(255) NOT NULL,
   `port` INT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `node_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `node_role` SMALLINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `node_machine`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `node_template_id` BIGINT NOT NULL,
   `machine_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `machine_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `cloud_vendor` TINYINT NOT NULL,
   `platform` VARCHAR(255) NOT NULL,
   `core_number` INT NOT NULL,
   `memory` INT NOT NULL,
   `machine_type` VARCHAR(255) NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `node_image`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `node_template_id` BIGINT NOT NULL,
   `image_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `image_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `cloud_vendor` TINYINT NOT NULL,
   `image_id` VARCHAR(255) NOT NULL,
   `region` VARCHAR(255) NOT NULL,
   `az` VARCHAR(255) NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `image_root_disk`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `image_template_id` BIGINT NOT NULL,
   `disk_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `image_data_disk`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `image_template_id` BIGINT NOT NULL,
   `disk_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `db_data_disk`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `db_template_id` BIGINT NOT NULL,
   `disk_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `disk_template`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL,
   `cloud_vendor` TINYINT NOT NULL,
   `type` VARCHAR(255) NOT NULL,
   `size` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `image_userdata`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `image_template_id` BIGINT NOT NULL,
   `userdata_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `userdata`(
	`id` BIGINT UNSIGNED AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`content` VARCHAR(4096) NOT NULL,
    `da_type` SMALLINT NOT NULL,
    `network_type` SMALLINT NOT NULL,
	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`is_del` TINYINT NOT NULL DEFAULT 0,
	 PRIMARY KEY ( `id` )

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `node_eip`(
   `id` BIGINT UNSIGNED AUTO_INCREMENT,
   `is_default` TINYINT NOT NULL DEFAULT 0,
   `node_template_id` BIGINT NOT NULL,
   `eip_template_id` BIGINT NOT NULL,
   `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `is_del` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `eip_template`(
	`id` BIGINT UNSIGNED AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
    `bind_width` INT NOT NULL,
	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`is_del` TINYINT NOT NULL DEFAULT 0,
	 PRIMARY KEY ( `id` )

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CREATE TABLE IF NOT EXISTS `userdata_arg`(
-- 	`id` BIGINT UNSIGNED AUTO_INCREMENT,
-- 	`userdata_template_id` BIGINT NOT NULL,
-- 	`position` TINYINT NOT NULL,
-- 	`value_type` TINYINT NOT NULL,
-- 	`created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- 	`modified_time` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- 	`is_del` TINYINT NOT NULL DEFAULT 0,
-- 	 PRIMARY KEY ( `id` )

-- )ENGINE=InnoDB DEFAULT CHARSET=utf8;